CREATE DATABASE ChallengeNetCore
ON PRIMARY (
NAME = N'ChallengeNetCore',
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\ChallengeNetCore.mdf',
SIZE = 10240 KB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1024 KB
)
LOG ON (
NAME = N'ChallengeNetCore_log',
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\ChallengeNetCore_log.ldf',
SIZE = 5120 KB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 10 %
)
GO

ALTER DATABASE ChallengeNetCore
SET
ANSI_NULL_DEFAULT OFF,
ANSI_NULLS OFF,
ANSI_PADDING OFF,
ANSI_WARNINGS OFF,
ARITHABORT OFF,
AUTO_CLOSE OFF,
AUTO_CREATE_STATISTICS ON,
AUTO_SHRINK OFF,
AUTO_UPDATE_STATISTICS ON,
AUTO_UPDATE_STATISTICS_ASYNC OFF,
CONCAT_NULL_YIELDS_NULL OFF,
CURSOR_CLOSE_ON_COMMIT OFF,
CURSOR_DEFAULT GLOBAL,
DATE_CORRELATION_OPTIMIZATION OFF,
DB_CHAINING OFF,
HONOR_BROKER_PRIORITY OFF,
MULTI_USER,
NESTED_TRIGGERS = ON,
NUMERIC_ROUNDABORT OFF,
PAGE_VERIFY CHECKSUM,
PARAMETERIZATION SIMPLE,
QUOTED_IDENTIFIER OFF,
READ_COMMITTED_SNAPSHOT OFF,
RECOVERY FULL,
RECURSIVE_TRIGGERS OFF,
TRANSFORM_NOISE_WORDS = OFF,
TRUSTWORTHY OFF
WITH ROLLBACK IMMEDIATE
GO

ALTER DATABASE ChallengeNetCore
SET DISABLE_BROKER
GO

ALTER DATABASE ChallengeNetCore
SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE ChallengeNetCore
SET FILESTREAM (NON_TRANSACTED_ACCESS = OFF)
GO

ALTER DATABASE ChallengeNetCore
SET QUERY_STORE = OFF
GO

USE ChallengeNetCore
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

EXEC ChallengeNetCore.sys.sp_addextendedproperty N'MS_Description'
                                               , 'ChallengeNetCore Database'
GO